### ISSUE TITLE
书籍下载不了

### ISSUE THREAD

**Issue by linzheming** [acm-clan/algorithm-stone#6]
<Error>
<Code>AccessDenied</Code>
<Message>You are denied by bucket referer policy.</Message>
<RequestId>614049B753BCC63339F46B97</RequestId>
<HostId>v8cloud.oss-cn-hangzhou.aliyuncs.com</HostId>
<BucketName>v8cloud</BucketName>
</Error>

**Comment by dansen** [comment]
再试试看看

**Comment by dansen** [comment]
应该没啥问题了，关闭
