### ISSUE TITLE
关于codeforces,div以及进度的疑问

### ISSUE THREAD

**Issue by songxujay** [acm-clan/algorithm-stone#8]
您好，

想问想一下 "Codeforces Div.3 Div.2路线图" 这个标题的codeforces和div是代表什么？以及进度指的是什么？ 

谢谢

**Comment by dansen** [comment]
codeforces是算竞平台，你可以网上搜索一下
网址：https://codeforces.com/

**Comment by songxujay** [comment]
好的谢谢

**Comment by gxsoar** [comment]
您好，请问codeforces有训练路线吗？是跟着比赛做还是按照专题刷，主要是个人思维能力比较差，想通过这个锻炼思维

**Comment by dansen** [comment]
> 您好，请问codeforces有训练路线吗？是跟着比赛做还是按照专题刷，主要是个人思维能力比较差，想通过这个锻炼思维

如果能跟着比赛做就跟着比赛，其余时间查漏补缺呗
